import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { Provider } from 'react-redux';
import { store } from '../redux/store';

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
    return (
        <>
            <Provider store={store}>
                <Head>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                </Head>
                <div className="flex flex-col justify-between h-screen">
                    <div className="container mx-auto">
                        <Header />
                        <Component {...pageProps} />
                    </div>
                    <Footer />
                </div>
            </Provider>
        </>
    );
}

export default MyApp;
